### ISSUE TITLE
SPIKE: Sector map with gains and losses per company

### ISSUE THREAD

**Issue by srimel** [srimel/stock-tracker#4]
Figure out API calls / data needed for this.

We also need to figure out what charting library we want to use for this one. 
- ChartJS or D3.js?

**Comment by jpb7** [comment]
Don't know if this has been noted elsewhere, but finnhub has sector metrics [here](https://finnhub.io/docs/api/sector-metrics). Requires premium subscription, though, and it's actually kind of hard to determine what that even means.

**Comment by srimel** [comment]
So I've been using ApexCharts for easily creating candlestick charts for stocks, I also see they have one that might work for this feature. It's called a [Treemap chart](https://apexcharts.com/docs/chart-types/treemap-chart/)
